- name: mirror-repository
  # You may pin to the exact commit or the version.
  # uses: yesolutions/mirror-action@082a9611ed4b64c796245a62b34584ee2ded6833
  uses: yesolutions/mirror-action@v0.6.0
  with:
    # The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes.
    REMOTE_NAME: # optional
    # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
    REMOTE: # optional
    # Username for remote repository
    GIT_USERNAME: # optional
    # The git https password or token for the remote repository
    GIT_PASSWORD: # optional
    # The ssh private key for writing to the remote repository, if using ssh
    GIT_SSH_PRIVATE_KEY: # optional
    # The ssh public key for writing to the remote repository. Normally, not required at all
    GIT_SSH_PUBLIC_KEY: # optional
    # The contents of a SSH known_hosts file for host key verification
    GIT_SSH_KNOWN_HOSTS: # optional
    # if true, skips host key verification. Mutually exclusive with GIT_SSH_KNOWN_HOSTS
    GIT_SSH_NO_VERIFY_HOST: # optional, default is false
    # Push all refs instead of just the current branch
    PUSH_ALL_REFS: # optional, default is true
    # The arugments to use when pushing the repository
    GIT_PUSH_ARGS: # optional, default is --tags --force --prune
    # set to "true" to enable debug mode
    DEBUG: # optional, default is false
